from e2b import Template, wait_for_port
from dotenv import load_dotenv
load_dotenv()

template = (
    Template()
    .from_ubuntu_image("22.04")
    .run_cmd("curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -")
    .apt_install(["nodejs"])
    .set_workdir("/home/user/project")
    .run_cmd("npm create vite@latest my-app -- --template react-ts")
    .set_workdir("/home/user/project/my-app")
    .run_cmd("npm install")
    .run_cmd("rm -f vite.config.ts vite.config.js")
    .run_cmd("echo \"import { defineConfig } from 'vite'\" > vite.config.ts")
    .run_cmd("echo \"import react from '@vitejs/plugin-react'\" >> vite.config.ts")
    .run_cmd("echo \"\" >> vite.config.ts")
    .run_cmd("echo \"export default defineConfig({\" >> vite.config.ts")
    .run_cmd("echo \"  plugins: [react()],\" >> vite.config.ts")
    .run_cmd("echo \"  server: {\" >> vite.config.ts")
    .run_cmd("echo \"    host: '0.0.0.0',\" >> vite.config.ts")
    .run_cmd("echo \"    port: 5173,\" >> vite.config.ts")
    .run_cmd("echo \"    strictPort: true,\" >> vite.config.ts")
    .run_cmd("echo \"    allowedHosts: ['.e2b.app', 'localhost'],\" >> vite.config.ts")
    .run_cmd("echo \"    hmr: {\" >> vite.config.ts")
    .run_cmd("echo \"      clientPort: 5173\" >> vite.config.ts")
    .run_cmd("echo \"    }\" >> vite.config.ts")
    .run_cmd("echo \"  }\" >> vite.config.ts")
    .run_cmd("echo \"})\" >> vite.config.ts")
    .set_start_cmd("npm run dev -- --host 0.0.0.0", wait_for_port(5173))
)
